export const incTotalShopCounter = () => ({type:'INC_TOTAL_SHOP_COUNTER'})
export const decTotalShopCounter = () => ({type:'DEC_TOTAL_SHOP_COUNTER'})
export const corectTotalShopCounter = (localCount) => ({type:'CORECT_TOTAL_SHOP_COUNTER' , payload: localCount})
export const UIaddNewID = (id) => ({type:'UI_ADD_NEW_ID', payload: id})
export const UIdeleteID = (index) => ({type:'UI_DELETE_ID', payload:index})
export const resultAddNewID = (id) => ({type:'RESULT_ADD_NEW_ID', payload: id})
export const resultDeleteID = (index) => ({type:'RESULT_DELETE_ID', payload:index})
export const setLabelTotalCounter = (name) => ({type: 'SET_LABEL_TOTAL_COUNTER', payload: name})
export const resultDeleteTargetAllID = (id) => ({type: 'RESULT_DELETE_TARGET_ALL_ID', payload: id})
export const calculateAllSumBasket = (allPrice) => ({type: 'CALCULATE_ALL_SUM_BASKET', payload: allPrice})
export const setTargetItemID = (id) => ({type: 'SET_TARGET_ITEM_ID', payload: id})
export const navBarToggle = () => ({type: 'NAV_BAR_TOGGLE'})